- name: Ensure .ssh directory exists.
  file:
    dest: "{{ destination_key | dirname }}"
    mode: 0700
    state: directory
- name: Install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ destination_key }}"
    mode: 0600
- name: Install ssh key public
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ destination_key }}.pub"
    mode: 0644
- name: Set authorized key taken from file
  authorized_key:
    user: "{{ lookup('env', 'USER') }}"
    key: "{{ lookup('file', item) }}"
    state: present
  with_fileglob:
  - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
